In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [0]:
#!unzip '/content/gdrive/My Drive/hackathon/hackathon-upload.zip'

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from warnings import simplefilter
simplefilter(action='ignore',category=FutureWarning)
data_w_jul=pd.read_csv('/content/gdrive/My Drive/hackathon/hackathon-upload/Hackathon_Working_2019_Jul.csv',sep=',')
data_w_jul.head()

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

  PERIODCODE WEEK  HOUR  ...         MBRD          BRD                SKU
0   7/1/2019  W27     9  ...  UNSPECIFIED  UNSPECIFIED  08/16 LOOSE ITEMS
1   7/1/2019  W27     9  ...  UNSPECIFIED  UNSPECIFIED  08/16 LOOSE ITEMS
2   7/1/2019  W27     9  ...  UNSPECIFIED  UNSPECIFIED  08/16 LOOSE ITEMS
3   7/1/2019  W27     9  ...  UNSPECIFIED  UNSPECIFIED  08/16 LOOSE ITEMS
4   7/1/2019  W27     9  ...  UNSPECIFIED  UNSPECIFIED  08/16 LOOSE ITEMS

[5 rows x 22 columns]

In [3]:
data_w_jul['STORECODE'].nunique()
data_w_jul1= data_w_jul[['TOWN','STORECODE','OUTLET_TYPE']].groupby(['TOWN','STORECODE','OUTLET_TYPE']).count()
data_w_jul1.to_csv('/content/gdrive/My Drive/hackathon/hackathon-upload/code2-july/data_w_jul1.csv') 
data_w_jul1=pd.read_csv('/content/gdrive/My Drive/hackathon/hackathon-upload/code2-july/data_w_jul1.csv')
data_val=pd.read_csv('/content/gdrive/My Drive/hackathon/hackathon-upload/Hackathon_Validation_Data_2.0.csv',sep=',')
data_val1= data_val.iloc[:,3:]
data_val1

                         GRP                  SGRP  ... 11/1/2019 12/1/2019
0          HAIR CONDITIONERS     HAIR CONDITIONERS  ...       NaN       NaN
1      SHAMPOO - BY SEGMENTS               SACHETS  ...       NaN       NaN
2      SHAMPOO - BY SEGMENTS               SACHETS  ...       NaN       NaN
3       HAIR DYES     (1/76)  HAIR DYES     (1/76)  ...       NaN       NaN
4       HAIR DYES     (1/76)  HAIR DYES     (1/76)  ...       NaN       NaN
...                      ...                   ...  ...       ...       ...
36220   HAIR DYES     (1/76)  HAIR DYES     (1/76)  ...       NaN       NaN
36221            SKIN CREAMS     OTHER FACE CREAMS  ...       NaN       NaN
36222   HAIR DYES     (1/76)  HAIR DYES     (1/76)  ...       NaN       NaN
36223            SKIN CREAMS      MOIST  LTN/CREAM  ...       NaN       NaN
36224            EYE MAKE UP      LIQUID EYE LINER  ...       NaN       NaN

[36225 rows x 13 columns]

In [4]:
data_id=pd.read_csv('/content/gdrive/My Drive/hackathon/hackathon-upload/Hackathon_Ideal_Data.csv',sep=',')
data_id_july=data_id.loc[data_id['PERIODCODE']=='7/1/2019']
data_id_july1=data_id_july[['GRP','SGRP','SSGRP','CMP','MBRD','BRD']]
data_val2=data_val1[['GRP','SGRP','SSGRP','CMP','MBRD','BRD']]
data_val3 = pd.merge(data_val2, data_id_july1, on=['GRP','SGRP','SSGRP','CMP','MBRD','BRD'], how='left', indicator='july')
data_val3['july'] = np.where(data_val3['july'] == 'both', np.nan, 0)
data_val3

                         GRP                  SGRP  ...                 BRD july
0          HAIR CONDITIONERS     HAIR CONDITIONERS  ...       L'OREAL PARIS  NaN
1          HAIR CONDITIONERS     HAIR CONDITIONERS  ...       L'OREAL PARIS  NaN
2          HAIR CONDITIONERS     HAIR CONDITIONERS  ...       L'OREAL PARIS  NaN
3          HAIR CONDITIONERS     HAIR CONDITIONERS  ...       L'OREAL PARIS  NaN
4          HAIR CONDITIONERS     HAIR CONDITIONERS  ...       L'OREAL PARIS  NaN
...                      ...                   ...  ...                 ...  ...
999107  HAIR DYES     (1/76)  HAIR DYES     (1/76)  ...  STREAX HAIR COLOUR  NaN
999108           SKIN CREAMS     OTHER FACE CREAMS  ...      LAKME ABSOLUTE  0.0
999109  HAIR DYES     (1/76)  HAIR DYES     (1/76)  ...            BIOTIQUE  0.0
999110           SKIN CREAMS      MOIST  LTN/CREAM  ...                KAYA  0.0
999111           EYE MAKE UP      LIQUID EYE LINER  ...           COLOR BAR  0.0

[999112 rows x 7 columns]

In [5]:
data_val3.to_csv('/content/gdrive/My Drive/hackathon/hackathon-upload/code2-july/data_val3.csv') 
data_val1['july']=data_val3['july']
data_val_new=pd.merge(data_w_jul1.assign(key='x'), data_val1.assign(key='x'), on='key').drop('key', 1)
data_val_new

              TOWN STORECODE   OUTLET_TYPE  ... 11/1/2019 12/1/2019 july
0        Bangalore        N1  Grocer Large  ...       NaN       NaN  NaN
1        Bangalore        N1  Grocer Large  ...       NaN       NaN  NaN
2        Bangalore        N1  Grocer Large  ...       NaN       NaN  NaN
3        Bangalore        N1  Grocer Large  ...       NaN       NaN  NaN
4        Bangalore        N1  Grocer Large  ...       NaN       NaN  NaN
...            ...       ...           ...  ...       ...       ...  ...
7462345     Mumbai       N99  Grocer Large  ...       NaN       NaN  NaN
7462346     Mumbai       N99  Grocer Large  ...       NaN       NaN  NaN
7462347     Mumbai       N99  Grocer Large  ...       NaN       NaN  NaN
7462348     Mumbai       N99  Grocer Large  ...       NaN       NaN  NaN
7462349     Mumbai       N99  Grocer Large  ...       NaN       NaN  NaN

[7462350 rows x 17 columns]

In [0]:
data_val_new.to_csv('/content/gdrive/My Drive/hackathon/hackathon-upload/code2-july/data_val_new.csv') 
data_val_new.isna().sum(axis = 0)
data_w_jul3= data_w_jul[['STORECODE','DAY','VALUE']].groupby(['STORECODE','DAY']).sum()
data_w_jul3.to_csv('/content/gdrive/My Drive/hackathon/hackathon-upload/code2-july/data_w_jul3.csv')
data_w_jul4=data_w_jul3.groupby(['STORECODE']).size().reset_index(name='Count')
data_w_jul5= data_w_jul[['TOWN','STORECODE','OUTLET_TYPE','GRP','SGRP','SSGRP','CMP','MBRD','BRD','SKU','VALUE']].groupby(['TOWN','STORECODE','OUTLET_TYPE','GRP','SGRP','SSGRP','CMP','MBRD','BRD','SKU']).sum()

In [7]:
data_w_jul5.to_csv('/content/gdrive/My Drive/hackathon/hackathon-upload/code2-july/data_w_jul5.csv') 
data_w_jul5=pd.read_csv('/content/gdrive/My Drive/hackathon/hackathon-upload/code2-july/data_w_jul5.csv')
data_w_jul6=pd.merge(data_w_jul5,data_w_jul4, on=['STORECODE'])
data_w_jul6["TOTAL_VALUE_31"]=data_w_jul6['VALUE']/data_w_jul6['Count']*31
data_w_jul6.drop(['VALUE','Count'], axis = 1, inplace=True)
data_w_jul6.rename(columns = {'TOTAL_VALUE_31':'july'}, inplace = True)
data_w_jul6

            TOWN STORECODE  ...                             SKU   july
0      Bangalore        N1  ...    05/17 SIGNTUR TEMP CDB 50 ML  118.0
1      Bangalore        N1  ...                 08/16 UN MAPPED  266.0
2      Bangalore        N1  ...  01/17 SANGHVI STICK CDB 110 NO  469.0
3      Bangalore        N1  ...   06/05                   20 NO   15.0
4      Bangalore        N1  ...    02/14 BLACK STONE CDB 115 NO  104.0
...          ...       ...  ...                             ...    ...
57529     Mumbai       N99  ...     12/18 LEMON & MINT PPH 1 KG  530.0
57530     Mumbai       N99  ...     10/18 JASMIN&ROSE PPH 500GM  106.0
57531     Mumbai       N99  ...  12/18 LEMON&CHANDAN PPH 800 GM   56.0
57532     Mumbai       N99  ...          12/16 DET PWD PPH 1 KG  110.0
57533     Mumbai       N99  ...  12/16 MAHA SHAKTISHLI PPH 500G   28.0

[57534 rows x 11 columns]

In [8]:
data_val_new1=data_val_new[['TOWN','STORECODE','OUTLET_TYPE','GRP','SGRP','SSGRP','CMP','MBRD','BRD','SKU','july']]
data_val_new2= data_val_new1.combine_first(data_w_jul6)
data_val_new2

              TOWN STORECODE  ...                             SKU   july
0        Bangalore        N1  ...    03/18 TTL RPR LCT PPH 5.5 ML  118.0
1        Bangalore        N1  ...      09/18 SMTH&SLKY PPH 8.5 ML  266.0
2        Bangalore        N1  ...       09/18 COLMTHOL PPH 8.5 ML  469.0
3        Bangalore        N1  ...       04/11 NTRL BLACK PPH 3 GM   15.0
4        Bangalore        N1  ...  05/14 2IN1 PK AML HNA PPH 5 GM  104.0
...            ...       ...  ...                             ...    ...
7462345     Mumbai       N99  ...    05/15 NTRL BLACK 1 CDB 60 ML    NaN
7462346     Mumbai       N99  ...  07/19 ABSL NGHT ESSNC CDB 15ML    NaN
7462347     Mumbai       N99  ...           06/10 HENNA CDB 90 GM    NaN
7462348     Mumbai       N99  ...  04/19 INTNSE HYD BDY LTN 100ML    NaN
7462349     Mumbai       N99  ...  07/16 WTRPRF EYELNER CDB 2.5ML    NaN

[7462350 rows x 11 columns]

In [9]:
data_val_new2.isnull().sum(axis = 0)

TOWN                 0
STORECODE            0
OUTLET_TYPE          0
GRP                  0
SGRP                 0
SSGRP                0
CMP                  0
MBRD                 0
BRD                  0
SKU                  0
july           7402976
dtype: int64

In [0]:
data_val_new2.to_csv('/content/gdrive/My Drive/hackathon/hackathon-upload/code2-july/data_val_new2.csv')

In [11]:
#data_val_new2= pd.read_csv('/content/gdrive/My Drive/hackathon/hackathon-upload/code2-july/data_val_new2.csv') 
GRP= list(data_val_new2.GRP.unique())
len(GRP)

164

In [0]:
GRP1=GRP[:30]
GRP2=GRP[30:165]

In [0]:
data_val_new3= data_val_new2[['GRP','SGRP','SSGRP','CMP','MBRD','BRD','july']]

In [14]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import GradientBoostingRegressor

final1=pd.DataFrame(columns=['GRP','SGRP','SSGRP','CMP','MBRD','BRD','7/1/2019'])
for i in GRP1:
    data_val_new4=data_val_new3[data_val_new3['GRP']==i]
    dummy_variables = ['GRP','SGRP','SSGRP','CMP','MBRD','BRD']
    for var in dummy_variables:
        dummy = pd.get_dummies(data_val_new4[var], prefix = var, drop_first = False)
        train = pd.concat([data_val_new4, dummy], axis = 1)
    train = train.drop(dummy_variables, axis = 1)
    train_1 = train[pd.isnull(train['july']) == False]
    train_2 = train[pd.isnull(train['july'])]
    
    X_1=train_1.iloc[:,1:].values
    y_1=train_1.iloc[:,0].values
    X_2=train_2.iloc[:,1:].values
    y_2=train_2.iloc[:,0].values
    
    gbr = GradientBoostingRegressor(n_estimators=100,max_depth=10, random_state=0)
    
    gbr.fit(X_1, y_1)

    generatedValues = gbr.predict(X_2)
    train_2['july'] = generatedValues
    data = train_1.append(train_2)
    data.sort_index(inplace=True)
    data_val_new4["7/1/2019"]=data['july']
    data_val_new4.drop(['july'], axis = 1, inplace=True)
    final1=final1.append(data_val_new4)
final1

                               GRP  ...     7/1/2019
0                HAIR CONDITIONERS  ...   118.000000
664              HAIR CONDITIONERS  ...  1935.000000
665              HAIR CONDITIONERS  ...   124.000000
666              HAIR CONDITIONERS  ...   220.000000
667              HAIR CONDITIONERS  ...   356.000000
...                            ...  ...          ...
7461691  COCONUT OIL PKTYP (08/02)  ...   483.185296
7461692  COCONUT OIL PKTYP (08/02)  ...   483.185296
7461707  COCONUT OIL PKTYP (08/02)  ...   226.903174
7461973  COCONUT OIL PKTYP (08/02)  ...   403.440414
7462207  COCONUT OIL PKTYP (08/02)  ...   303.810465

[4011644 rows x 7 columns]

In [0]:
final1.to_csv('/content/gdrive/My Drive/hackathon/hackathon-upload/code2-july/final1.csv',index=False)

In [16]:
final2=pd.DataFrame(columns=['GRP','SGRP','SSGRP','CMP','MBRD','BRD','7/1/2019'])
for i in GRP2:
    data_val_new4=data_val_new3[data_val_new3['GRP']==i]
    dummy_variables = ['GRP','SGRP','SSGRP','CMP','MBRD','BRD']
    for var in dummy_variables:
        dummy = pd.get_dummies(data_val_new4[var], prefix = var, drop_first = False)
        train = pd.concat([data_val_new4, dummy], axis = 1)
    train = train.drop(dummy_variables, axis = 1)
    train_1 = train[pd.isnull(train['july']) == False]
    train_2 = train[pd.isnull(train['july'])]
    
    X_1=train_1.iloc[:,1:].values
    y_1=train_1.iloc[:,0].values
    X_2=train_2.iloc[:,1:].values
    y_2=train_2.iloc[:,0].values
    
    gbr = GradientBoostingRegressor(n_estimators=100,max_depth=10, random_state=0)
    
    gbr.fit(X_1, y_1)

    generatedValues = gbr.predict(X_2)
    train_2['july'] = generatedValues
    data = train_1.append(train_2)
    data.sort_index(inplace=True)
    data_val_new4["7/1/2019"]=data['july']
    data_val_new4.drop(['july'], axis = 1, inplace=True)
    final2=final2.append(data_val_new4)
final2

                          GRP  ...     7/1/2019
101      HAIR OILS PKTP(8/02)  ...    19.200000
102      HAIR OILS PKTP(8/02)  ...   180.000000
103      HAIR OILS PKTP(8/02)  ...   100.000000
298      HAIR OILS PKTP(8/02)  ...  5672.000000
299      HAIR OILS PKTP(8/02)  ...   140.000000
...                       ...  ...          ...
7317155    BULK PACKAGED RICE  ...    41.333333
7353380    BULK PACKAGED RICE  ...    41.333333
7389605    BULK PACKAGED RICE  ...    41.333333
7425830    BULK PACKAGED RICE  ...    41.333333
7462055    BULK PACKAGED RICE  ...    41.333333

[3450706 rows x 7 columns]

In [0]:
final2.to_csv('/content/gdrive/My Drive/hackathon/hackathon-upload/code2-july/final2.csv', index=False)

In [0]:
#final1= pd.read_csv('/content/gdrive/My Drive/hackathon/hackathon-upload/code2-july/final1.csv') 
#final2= pd.read_csv('/content/gdrive/My Drive/hackathon/hackathon-upload/code2-july/final2.csv')

In [18]:
final_all = final1.append(final2)
final_all.sort_index(inplace=True)
final_all

                           GRP  ...     7/1/2019
0            HAIR CONDITIONERS  ...   118.000000
1        SHAMPOO - BY SEGMENTS  ...   266.000000
2        SHAMPOO - BY SEGMENTS  ...   469.000000
3         HAIR DYES     (1/76)  ...    15.000000
4         HAIR DYES     (1/76)  ...   104.000000
...                        ...  ...          ...
7462345   HAIR DYES     (1/76)  ...  5784.903474
7462346            SKIN CREAMS  ...   344.323663
7462347   HAIR DYES     (1/76)  ...    98.065777
7462348            SKIN CREAMS  ...   344.323663
7462349            EYE MAKE UP  ...   310.445965

[7462350 rows x 7 columns]

In [0]:
final_all.to_csv('/content/gdrive/My Drive/hackathon/hackathon-upload/code2-july/final_all.csv', index=False)

In [0]:
data_val_new2['7/1/2019']=final_all['7/1/2019']
data_val_new2.drop(['july'], axis = 1, inplace=True)

In [0]:
data_val_new2.to_csv('/content/gdrive/My Drive/hackathon/hackathon-upload/code2-july/final_july.csv', index=False)

In [0]:
#data_val_final.drop(['july'], axis = 1, inplace=True)

In [0]:
#data_val_final.to_csv('/content/gdrive/My Drive/hackathon/hackathon-upload/code2-july/data_val_final.csv')